variable "syscores" {
  type = number
  default = 4
}

locals {
  cpus = min(var.syscores, 4)
  memory = min(4096, local.cpus * 512)
}

variable "outname" {
  type    = string
  default = "memcached"
}

variable "base_img" {
  type    = string
  default = "/simbricks/images/output-base/base"
}

variable "compressed" {
  type    = bool
  default = false
}

source "qemu" "autogenerated_1" {
  communicator     = "ssh"
  cpus             = "${local.cpus}"
  disk_image       = true
  disk_compression = "${var.compressed}"
  headless         = true
  iso_checksum     = "none"
  iso_url          = "${var.base_img}"
  memory           = "${local.memory}"
  net_device       = "virtio-net"
  output_directory = "output-${var.outname}"
  qemuargs         = [["-machine", "pc-q35-4.2,accel=kvm:tcg,usb=off,vmport=off,dump-guest-core=off"]]
  shutdown_command = "sudo shutdown --poweroff --no-wall now"
  ssh_password     = "ubuntu"
  ssh_username     = "ubuntu"
  use_backing_file = "true"
  vm_name          = "${var.outname}"
}

build {
  sources = ["source.qemu.autogenerated_1"]

  provisioner "file" {
    direction = "upload"
    source = "input-${var.outname}"
    destination = "/tmp/input"
  }

  provisioner "shell" {
    execute_command = "{{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["image/install.sh", "image/cleanup.sh"]
  }

}
